### ISSUE TITLE
umu-launcher crashes with no network connection

### ISSUE THREAD

**Issue by 7oxicshadow** [Open-Wine-Components/ULWGL#166]
As per title. If you try to run umu-launcher without access to the internet it will crash with the following:
```

ERROR:  [Errno 101] Network is unreachable
Traceback (most recent call last):
  File "/mnt/linuxfiles_8tb/custom_wine/umu-launcher/share/umu/umu_run.py", line 629, in <module>
    sys.exit(main())
             ^^^^^^
  File "/mnt/linuxfiles_8tb/custom_wine/umu-launcher/share/umu/umu_run.py", line 611, in main
    future.result()
  File "/usr/lib64/python3.12/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib64/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/linuxfiles_8tb/custom_wine/umu-launcher/share/umu/umu_runtime.py", line 189, in setup_umu
    _update_umu(local, json, thread_pool)
  File "/mnt/linuxfiles_8tb/custom_wine/umu-launcher/share/umu/umu_runtime.py", line 283, in _update_umu
    client_session.request(
  File "/usr/lib64/python3.12/http/client.py", line 1336, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.12/http/client.py", line 1382, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.12/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.12/http/client.py", line 1091, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.12/http/client.py", line 1035, in send
    self.connect()
  File "/usr/lib64/python3.12/http/client.py", line 1470, in connect
    super().connect()
  File "/usr/lib64/python3.12/http/client.py", line 1001, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/socket.py", line 853, in create_connection
    raise exceptions[0]
  File "/usr/lib64/python3.12/socket.py", line 838, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable
```

**Comment by R1kaB3rN** [comment]
I can tell your version of umu-launcher is out of date, and I believe that `OSError` should be addressed in the latest branch. Please report back after updating to the latest umu.

**Comment by 7oxicshadow** [comment]
I still get the error with what I think is the latest master installed. (some of the line numbers are different now)

```
ERROR:  [Errno 101] Network is unreachable
Traceback (most recent call last):
  File "/mnt/linuxfiles_8tb/custom_wine/umu-launcher/share/umu/umu_run.py", line 864, in <module>
    sys.exit(main())
             ^^^^^^
  File "/mnt/linuxfiles_8tb/custom_wine/umu-launcher/share/umu/umu_run.py", line 845, in main
    future.result()
  File "/usr/lib64/python3.12/concurrent/futures/_base.py", line 456, in result
    return self.__get_result()
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/concurrent/futures/_base.py", line 401, in __get_result
    raise self._exception
  File "/usr/lib64/python3.12/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/linuxfiles_8tb/custom_wine/umu-launcher/share/umu/umu/umu_runtime.py", line 198, in setup_umu
    _update_umu(local, json, thread_pool)
  File "/mnt/linuxfiles_8tb/custom_wine/umu-launcher/share/umu/umu/umu_runtime.py", line 312, in _update_umu
    client_session.request(
  File "/usr/lib64/python3.12/http/client.py", line 1336, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib64/python3.12/http/client.py", line 1382, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.12/http/client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib64/python3.12/http/client.py", line 1091, in _send_output
    self.send(msg)
  File "/usr/lib64/python3.12/http/client.py", line 1035, in send
    self.connect()
  File "/usr/lib64/python3.12/http/client.py", line 1470, in connect
    super().connect()
  File "/usr/lib64/python3.12/http/client.py", line 1001, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.12/socket.py", line 853, in create_connection
    raise exceptions[0]
  File "/usr/lib64/python3.12/socket.py", line 838, in create_connection
    sock.connect(sa)
OSError: [Errno 101] Network is unreachable
```

Its late here so I will try again tomorrow with a clean install.

**Comment by R1kaB3rN** [comment]
Hmm, it looks like that `OSError` occurs when attempting to request the `VERSIONS.txt` file from the [public beta endpoint](https://repo.steampowered.com/steamrt3/images/latest-container-runtime-public-beta/) because the socket object wasn't able to be created during the process. 

While I can handle the error returned from the umu update thread, I cannot reproduce this and you'll still run into the problem of not being able to update the runtime in the future. I find it strange that you can initially connect to 1.1.1.1 (Cloudflare), but cannot connect to `repo.steampowered.com` (which is behind a Cloudflare proxy).

If this was working but just stopped all of a sudden, then it tells me it's not a problem with the launcher. Was this the case for you?

**Comment by R1kaB3rN** [comment]
Closing as this issue cannot be reproduced and for inactivity.

While the `OSError` can be handled after [waiting for the update thread](https://github.com/Open-Wine-Components/umu-launcher/blob/main/umu/umu_run.py#L860), I expect you to run into a critical problem of never being able to update the Steam Runtime. That issue cannot be handled and would be outside of our control unless we build and host the runtime at another endpoint.
